document.write("<h1>Welcome to my website.</h1>")
document.write("<i><h3>My self Divyesh Modasiya.</h3></i>")
document.write("<i><h3>I'm from Jetpur city.</h3></i>")
document.write("<i><h3>I Completed my 12th at Dhlakiya School Rajkot.</h3></i>")
document.write("<i><h3>I Completed my graduation at Atmiya Univercity Rajkot.</h3></i>")
document.write("<i><h3>I Completed BCA from Rajkot</h3></i>")
document.write("<i><h3>Curently i am doing Full Stack Devlpoment at R&W</h3></i>")
document.write("<i><h3>Curently i am 21 year old</h3></i>")
document.write("<i><h3>I love to Exploring world and traveling diffrent places</h3></i>")
document.write("<i><h3>Also i love to play sports</h3></i>")